In [96]:
import tensorflow as tf

In [97]:
tf.__version__

'2.4.0'

In [98]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [99]:
env=gym.make("FrozenLake-v0")

In [100]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [101]:
num_episodes=20000
max_steps_per_episode=200
learning_rate=0.1
discount_rate=0.99
exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.001


In [102]:
rewards_all_episodes=[]


for episode in range(num_episodes):
    state = env.reset()
    done=False
    rewards_in_current_episode=0
    for step in range(max_steps_per_episode):        
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) # chooses the highest Q value from the q_table
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        q_table[state,action]=q_table[state,action]*(1-learning_rate)+ learning_rate * (reward+discount_rate * np.max(q_table[new_state, :]))
        
        state= new_state
        rewards_in_current_episode += reward
        
        if done==True:
            break        
        
    exploration_rate = min_exploration_rate + (max_exploration_rate-min_exploration_rate) * np.exp(-1 * exploration_decay_rate * episode)
    rewards_all_episodes.append(rewards_in_current_episode)


In [103]:
print(q_table)

[[0.5194077  0.51562204 0.5007771  0.51500113]
 [0.28577758 0.31541652 0.28156082 0.48590408]
 [0.3885722  0.22298445 0.24441882 0.25656546]
 [0.06495436 0.12156498 0.00125298 0.0590754 ]
 [0.52981897 0.40088994 0.33511423 0.3450728 ]
 [0.         0.         0.         0.        ]
 [0.14742769 0.17542188 0.24405786 0.05825399]
 [0.         0.         0.         0.        ]
 [0.47067141 0.39214867 0.4863353  0.56125581]
 [0.43337317 0.60552734 0.41785305 0.41810386]
 [0.65523391 0.40628195 0.41868659 0.25914597]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.37522895 0.66515493 0.76612986 0.52779697]
 [0.72911076 0.88935133 0.76228992 0.78859803]
 [0.         0.         0.         0.        ]]


In [104]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)

In [105]:
count = 1000
for r in rewards_per_thousand_episodes:
    print(count, " : ", str(sum(r/1000)))
    count+=1000

1000  :  0.03900000000000003
2000  :  0.18800000000000014
3000  :  0.4180000000000003
4000  :  0.5610000000000004
5000  :  0.6010000000000004
6000  :  0.6340000000000005
7000  :  0.6650000000000005
8000  :  0.6890000000000005
9000  :  0.6670000000000005
10000  :  0.6660000000000005
11000  :  0.6990000000000005
12000  :  0.6960000000000005
13000  :  0.6650000000000005
14000  :  0.6800000000000005
15000  :  0.6650000000000005
16000  :  0.6880000000000005
17000  :  0.6910000000000005
18000  :  0.6760000000000005
19000  :  0.6800000000000005
20000  :  0.6870000000000005


In [106]:
## Inference

In [108]:
for episode in range(3):
    state = env.reset()
    done=False
    print("** Episode : ", episode+1, "**\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):      
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(q_table[state,:])     
        new_state, reward, done, info = env.step(action)
                
        rewards_in_current_episode += reward
        
        if done==True:
            clear_output(wait=True)
            env.render()
            if reward==1:
                print("*Goal*")
                time.sleep(3)
            else:
                print("*Hole*")
                time.sleep(3)
            clear_output(wait=True)
            break        
        state= new_state
        
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
*Goal*
