In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.0'

## Consntants

In [5]:
a = tf.constant([[4,3],[2,4]])

In [6]:
print(a)

tf.Tensor(
[[4 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [4]:
a.shape

TensorShape([2, 2])

## Variable

In [8]:
v=tf.Variable([[4,1],[2,2]])

In [9]:
v

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[4, 1],
       [2, 2]], dtype=int32)>

In [10]:
v.shape

TensorShape([2, 2])

## Concat

In [11]:
a = tf.constant([[1,2],[3,4]])

In [13]:
b = tf.constant([[5,6],[7,8]])

In [15]:
tf.concat(values=[a,b],axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [16]:
tf.concat(values=[a,b],axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

In [18]:
c = tf.Variable([[1,2],[3,4]])

In [19]:
d = tf.constant([[5,6],[7,8]])

In [20]:
tf.concat(values=[c,d],axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

## Filling tensors

In [26]:
zeros = tf.zeros(shape=[2,3],dtype=tf.int32)

In [27]:
zeros

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [28]:
ones = tf.ones(shape=[3,4], dtype=tf.float16)

In [29]:
ones

<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)>

In [34]:
tf.reshape(ones,shape=[4,3])

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)>

In [38]:
tf.random.uniform(shape=[2,4],dtype=tf.float16)

<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[0.966 , 0.288 , 0.3984, 0.2373],
       [0.831 , 0.    , 0.4814, 0.4834]], dtype=float16)>

## Casting

In [42]:
float_tensor = tf.constant([[3.1,4.1],[5.1,6.1]], dtype=tf.float16)

In [43]:
float_tensor

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[3.1, 4.1],
       [5.1, 6.1]], dtype=float16)>

In [44]:
tf.cast(float_tensor, dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

## Transpose

In [46]:
tf.transpose(ones)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)>

## Operations

In [47]:
a = tf.constant([[1,2],[3,4]])

In [51]:
b = tf.constant([[5],[6]])

In [56]:
ab = tf.matmul(a,b)

In [53]:
ab

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[17],
       [39]], dtype=int32)>

In [54]:
a * b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [18, 24]], dtype=int32)>

## Identity matrix

In [61]:
tf.eye(num_rows=3,num_columns=3, dtype=tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)>