In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([[1,2,3],[4,5,6]])

In [3]:
b=tf.constant([[2],[3]])

In [4]:
c  =a * b

In [5]:
c.shape

TensorShape([2, 3])

In [9]:
x = tf.sparse.SparseTensor(indices=[[0,0],[1,2]],values=[1,2],dense_shape=[3,4])

In [13]:
tf.sparse.to_dense(x)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [15]:
x=tf.constant([[[1],[2],[3]],[[4],[5],[6]]])

In [17]:
x.shape

TensorShape([2, 3, 1])

In [20]:
tf.rank(x)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [21]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=6>